# pylint: disable-all
# Generated by Django 3.2.23 on 2024-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('TERM 1', 'TERM 1'), ('TERM 2', 'TERM 2'), ('TERM 3', 'TERM 3'), ('TERM 4', 'TERM 4')], max_length=200),
        ),
    ]
